rvm:
   - 1.9.3
before_script:
  - sudo pip install -e git://github.com/tswicegood/armstrong.dev.git@env#egg=armstrong.dev.git
  - sudo pip install -r requirements/dev.txt
  - sudo pip install .
env:
  - SKIP_COVERAGE=1
  - SKIP_INSTALL=1
script:
  - fab test