language: python
python:
 - 2.7
install:
  - pip install -i http://armstrong.github.com/pypi.armstrongcms.org/index/ -r requirements/dev.txt
  - pip install .
env:
  - SKIP_COVERAGE=1 SKIP_INSTALL=1
script: fab test
notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#armstrongcms"
