language: python
python:
  - "2.7"
install: pip install -r requirements/dev.txt ; pip install .
env:
  - SKIP_COVERAGE=1 SKIP_INSTALL=1
script: fab test
notifications:
  email: false
  irc:
    - "irc.freenode.net#armstrongcms"
